name: Test build backend

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-backend:
    name: Build backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24.x
          cache: npm
          cache-dependency-path: "**/package-lock.json"
      - name: Install backend dependencies
        run: npm ci
        working-directory: backend
      - name: Build backend
        run: npm run build
        working-directory: backend